backend:
  name: github
  repo: FaiChou/netlify-cms-tutorial

media_folder: static/assets
public_folder: /assets
site_url: https://keen-murdock-512d1f.netlify.com
logo_url: https://raw.githubusercontent.com/FaiChou/netlify-cms-tutorial/master/static/favicon.ico

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }